version: '3.8'

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:latest
    container_name: voi_lavalink
    restart: always
    environment:
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    ports:
      - "2333:2333"

  bot:
    build: .
    container_name: voi_bot
    restart: always
    environment:
      - DISCORD_TOKEN=YOUR_ACTUAL_TOKEN_HERE
      - LAVALINK_URL=http://lavalink:2333
      - LAVALINK_PASSWORD=youshallnotpass
    depends_on:
      - lavalink
